source 'https://rubygems.org'
ruby '4.0.0'

gem 'rails', '~> 8.1'
gem 'pg', '~> 1.1'
gem 'puma', '>= 5.0'
gem 'bootsnap', require: false

# Auth
gem 'rodauth-rails', '~> 2.1'
gem 'rodauth-model', '~> 0.4'
gem 'jwt', '~> 2.8'
gem 'bcrypt', '~> 3.1'

# Multi-tenancy
gem 'acts_as_tenant', '~> 1.0'

# Authorization
gem 'pundit', '~> 2.3'

# Pagination
gem 'kaminari', '~> 1.2'

# CORS
gem 'rack-cors', '~> 2.0'

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[windows jruby]

# Enables Sequel to use Active Record's database connection
gem 'sequel-activerecord_connection', '~> 2.0', require: false
# Used by Rodauth for rendering built-in view and email templates
gem 'tilt', '~> 2.4', require: false

group :development, :test do
  gem 'debug', platforms: %i[mri windows], require: 'debug/prelude'
  gem 'rspec-rails', '~> 7.0'
  gem 'factory_bot_rails', '~> 6.4'
  gem 'faker', '~> 3.2'
  gem 'bundler-audit', require: false
  gem 'brakeman', require: false
  gem 'rubocop-rails-omakase', require: false
end

group :test do
  gem 'shoulda-matchers', '~> 6.0'
end
